# Generated by Django 3.2.13 on 2025-06-16 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('airplane_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=10, null=True)),
                ('first_class_seats', models.PositiveSmallIntegerField()),
                ('economy_class_seats', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('weekly_days', models.CharField(max_length=27)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrive_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booksystem.airplane')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='booksystem.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='booksystem.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id_card', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('cabin_class', models.CharField(choices=[('first', 'First Class'), ('economy', 'Economy Class')], max_length=7)),
                ('operation_date', models.DateField()),
                ('operation_type', models.CharField(choices=[('purchase', 'Purchase'), ('refund', 'Refund')], max_length=8)),
                ('transaction_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booksystem.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksystem.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksystem.city'),
        ),
        migrations.CreateModel(
            name='SecondFlight',
            fields=[
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booksystem.flight')),
                ('second_flight', models.CharField(max_length=7)),
                ('weekly_days', models.CharField(max_length=27)),
                ('transfer_date', models.DateField()),
                ('transfer_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booksystem.airplane')),
                ('transfer_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booksystem.airport')),
            ],
        ),
        migrations.CreateModel(
            name='CabinPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin_class', models.CharField(choices=[('first', 'First Class'), ('economy', 'Economy Class')], max_length=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('flightnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksystem.flight')),
            ],
            options={
                'unique_together': {('flightnumber', 'cabin_class')},
            },
        ),
    ]
