# Generated by Django 3.2.13 on 2025-06-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='airplane',
            index=models.Index(fields=['airplane_id'], name='booksystem__airplan_1aae39_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['airport_code'], name='booksystem__airport_7b92e3_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinpricing',
            index=models.Index(fields=['flightnumber', 'cabin_class'], name='booksystem__flightn_3dafb1_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['city_code'], name='booksystem__city_co_e72d48_idx'),
        ),
        migrations.AddIndex(
            model_name='passenger',
            index=models.Index(fields=['id_card'], name='booksystem__id_card_8e3bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='secondflight',
            index=models.Index(fields=['flight'], name='booksystem__flight__533cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionrecord',
            index=models.Index(fields=['passenger', 'operation_type', 'buyer'], name='booksystem__passeng_6ddb54_idx'),
        ),
    ]
